Adds Musicbrainz tags to lastfm plugin, PSA test, and plugin reload command
thomwiggers/onebot pull request #36
Opened 2017-02-02 05:47 UTC by mattbox

- Added code to use artist genre tags from Musicbrainz instead of the ones that Last.fm gives for response to the now playing command.
- Test file for PSA plugin
- Added `load` command to the botui module to reload plugins without restarting the bot
- Some minor code cleanup, formatting, and commenting

2017-02-03 11:19 UTC, thomwiggers requested changes
Overall I'm pretty happy with this change (and fairly excited for musicbrainz support 😃 ) but there are some small things that I think need to be fixed.

2017-02-03 11:19 UTC, thomwiggers commented on .gitignore
> +!track*.json
I'd prefer `!test/fixtures/*.json` as that makes it more explicit what's going on.

2017-02-03 11:19 UTC, thomwiggers commented on onebot/plugins/acl.py
> +        - ``all_permissions``: username depends on mask chosen
`all_permissions` isn't a setting, it's the permission given to the name in `superadmin`.

2017-02-03 11:19 UTC, thomwiggers commented on onebot/plugins/botui.py
> +    def load(self, mask, target, args):
Does this also work for plugins that are not already loaded? If not, there probably should be some error handling. If so, the help-text possibly needs to be updated.

2017-02-03 11:19 UTC, thomwiggers commented on onebot/plugins/botui.py
> +    def load(self, mask, target, args):
If it does work for 'new' loads, maybe change the help-text to `(re)loads`.

2017-02-03 11:19 UTC, thomwiggers commented on onebot/plugins/lastfm.py
> +        #         info['tags'] = [tag['name'] for tag in taglist]
Why comment this out. Either delete it or (alternatively) turn it into a configurable thing: either use mbrainz tags or use last.fm tags.

2017-02-03 11:19 UTC, thomwiggers commented on tests/test_plugin_lastfm.py
> +#####
Why this addition?

2017-02-04 07:42 UTC, mattbox commented on onebot/plugins/botui.py
> +    def load(self, mask, target, args):
I added some error handling to limit it to plugins that have already been loaded. I believe it's possible to load new plugins, but it's not really what the `reload()` method was intended for. I added this mainly for debugging and changing settings.

2017-02-04 13:30 UTC, thomwiggers requested changes
I think with this last small change it can be merged.

2017-02-04 13:30 UTC, thomwiggers commented on onebot/plugins/botui.py
> +    def load(self, mask, target, args):
Please rename the command / function to `reload` then for clarity.

2017-02-05 11:55 UTC, thomwiggers commented
Thanks a lot, I should bump releasing a new version higher up my todo list...

2017-02-05 11:56 UTC, merged